package com.leandro1995.seito.fcm.firestore.config

object Setting {
    const val USERS = "users"
    const val EMAIL = "email"
    const val NAME = "name"
    const val LAST_NAME = "last_name"
    const val AGE = "age"
    const val SEX = "sex"
    const val CODE = "code"
    const val TEACHER = "teacher"
    const val COINS = "coins"
    const val VIDEO_COURSE = "video_course"
    const val IMAGE_URL = "image_url"
    const val VIDEO_URL = "video_url"
    const val COURSE = "course"
    const val ID_LEVEL = "id_level"
    const val BALLOT = "ballot"
    const val OPTION_ARRAY = "option_array"
    const val ANSWER = "answer"
    const val EXERCISE = "exercise"
    const val DATE = "date"
    const val NOTE = "note"
    const val IS_ANSWER = "is_answer"
    const val TIMER = "timer"
    const val EXAM = "exam"
    const val QUESTION = "question"
}